package com.book.store.dao;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import lombok.Data;


@Entity
@Data
public class Book
{
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY) // ID should be generated by the database
	private Long id;
    private String title;
    private String author;
    private String genre;
    private String isbn;
    private Double price;
    private String description;
    private Integer stockQuantity;
    private String imageUrl;
    private String createdBy;
    
    
    @ManyToOne 
    @JoinColumn(name = "user_id") 
    private User user;

}
